<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="37723" started-at="2021-02-11T10:58:34Z" finished-at="2021-02-11T10:59:11Z">
    <groups>
    </groups>
    <test name="Test2" duration-ms="37723" started-at="2021-02-11T10:58:34Z" finished-at="2021-02-11T10:59:11Z">
      <class name="com.pom.testcases.Testsnapdeal">
        <test-method status="PASS" signature="launch(java.lang.String, java.lang.String)[pri:0, instance:com.pom.testcases.Testsnapdeal@91161c7]" name="launch" is-config="true" duration-ms="32564" started-at="2021-02-11T16:28:34Z" finished-at="2021-02-11T16:29:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.snapdeal.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="FAIL" signature="testcase1(java.lang.String)[pri:0, instance:com.pom.testcases.Testsnapdeal@91161c7]" name="testcase1" duration-ms="3798" started-at="2021-02-11T16:29:06Z" data-provider="get_product_data" finished-at="2021-02-11T16:29:10Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[Data provider mismatchMethod: testcase1([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])Arguments: [(java.lang.String) Mobile,null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: Data provider mismatchMethod: testcase1([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])Arguments: [(java.lang.String) Mobile,null]at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)at org.testng.internal.Parameters.injectParameters(Parameters.java:796)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:973)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method status="PASS" signature="tear_down()[pri:0, instance:com.pom.testcases.Testsnapdeal@91161c7]" name="tear_down" is-config="true" duration-ms="1277" started-at="2021-02-11T16:29:10Z" finished-at="2021-02-11T16:29:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear_down -->
      </class> <!-- com.pom.testcases.Testsnapdeal -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
